x-app-common: &app-common
  build:
    context: .
  # allow interactive input for debug (ipdb)
  stdin_open: true
  tty: true
  volumes:
    - .:/app
  depends_on:
    redis:
      condition: service_healthy

services:
  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./nginx_config:/etc/nginx/conf.d/
    depends_on:
      - api
      - frontend
    ports:
      - 8000:80
  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    command:
      - npm
      - start
    environment:
      CHOKIDAR_USEPOLLING: "true"
    depends_on:
      - api
    volumes:
      - .:/app
  api:
    <<: *app-common
    environment:
      UVICORN_HOST: 0.0.0.0
    command:
      - /bin/bash
      - -c
      - |
        python manage.py collectstatic --no-input
        uvicorn quantum_web.asgi:application --reload
  worker:
    <<: *app-common
    command:
      - /bin/bash
      - -c
      - |
        python manage.py qworker
  redis:
    image: redis:7.0.7-alpine
    healthcheck:
      test: [ "CMD", "redis-cli","ping" ]
      start_period: 30s
      interval: 10s
      timeout: 30s
      retries: 5
    volumes:
      - redis-data:/data

volumes:
  redis-data:
